#ifndef __PROTOCOL_H__
#define __PROTOCOL_H__

#ifdef __cplusplus
	extern "C" {
#endif

#define FRAMEHEAD 0x5A
#define REGION(msg) 1

typedef enum {
	ProtocolType = 0x0001,
}Protocol_Type;

typedef enum {
	ReportFlag_Respons = 0,
	ReportFlag_Auto = 1,
}Auto_Report;

typedef enum {
	MsgType_Err = 0,
	MsgType_ReaderConfig = 1,
	MsgType_RFIDConfig = 2,
	MsgType_ReaderLog = 3,
	MsgType_Update = 4,
	MsgType_TestCmd = 5,
}MsgType;

typedef enum {
#if REGION("读取和设置命令相同")
	READER_MID_GETREADER = 0x00,
	READER_MID_GETBASEV = 0x01,
	READER_MID_SETCOM = 0x02,
	READER_MID_GETCOM = 0x03,
	READER_MID_SETIP = 0x04,
	READER_MID_GETIP = 0x05,
	READER_MID_GETMAC = 0x6,
	READER_MID_SETCS = 0x07,
	READER_MID_GETCS = 0x08,
	READER_MID_SETGPO = 0x9,
	READER_MID_GETGPI_STATE = 0x0A,
	READER_MID_SETGPI_TRIGGER = 0x0B,
	READER_MID_GETGPI_TRIGGER = 0x0C,
	READER_MID_SETWIGAN = 0x0D,
	READER_MID_GETWIGAN = 0x0E,
	READER_MID_REBOOT = 0x0F,
	READER_MID_SETTIME = 0x10,
	READER_MID_GETTIME = 0x11,
	READER_MID_ACKCONN = 0x12,
	READER_MID_SETMAC = 0x13,
	READER_MID_RESET = 0x14,
	READER_MID_SET485 = 0x15,
	READER_MID_GET485 = 0x16,
	READER_MID_BUZZERSW = 0x1E,
	READER_MID_BUZZERCTRL = 0x1F,
	READER_MID_GETWHITELIST = 0x20,
	READER_MID_INSERTWHITELIST = 0x21,
	READER_MID_DELWHITELIST = 0x22,
	READER_MID_SETWHITELIST_ACTTIONPARA = 0x23,
	READER_MID_GETWHITELIST_ACTTIONPARA = 024,
	READER_MID_SETWHITELISTSW = 0x25,
	READER_MID_GETWHITELISTWS = 0x26,
	READER_MID_SETUDP = 0x27,
	READER_MID_GETUDP = 0x28,
	READER_MID_SETHTTP = 0x29,
	READER_MID_GETHTTP = 0x2A,
	READER_MID_SETWIFISEARCH = 0x31,
	READER_MID_GETWIFIRESULT = 0x32,
	READER_MID_SETWIFI = 0x33,
	READER_MID_GETWIFICONSTATE = 0x34,
	READER_MID_SETWIFINICPARA = 0x35,
	READER_MID_GETWIFINICPARA = 0x36,
	READER_MID_SETWIFINICSW = 0x37,
	READER_MID_GETWIFINICSW = 0x38,
	READER_MID_SETEAS = 0x3F,
	READER_MID_GETEAS = 0x40,
#endif 

#if REGION("断点续传")
	READER_MID_SETRESUME = 0x17,
	READER_MID_GETRESUME = 0x18,
	READER_MID_GETCACHE = 0x1B,
	READER_MID_CLEANCACHE = 0x1C,
#endif

#if REGION("读写器配置消息自动上报命令")
	READER_MID_TRIGGERSTART = 0x00,
	READER_MID_TRIGGEROVER = 0x01,
	READER_MID_ACKCONNSTATUS = 0x12,
#endif

#if REGION("读取和设置命令相同")
	RFID_MID_GETRFIDCAPATICY = 0x00,
	RFID_MID_SETPOWER = 0x01,
	RFID_MID_GETPOWER = 0x02,
	RFID_MID_SETRFBAUD = 0x03,
	RFID_MID_GETRFBAUD = 0x04,
	RFID_MID_SETWORKRF = 0x05,
	RFID_MID_GETWORKRF = 0x06,
	RFID_MID_SETEXTENDANTPARA = 0x07,
	RFID_MID_GETEXTENDANTPARA = 0x08,
	RFID_MID_SETTAGREPORTPARA = 0x09,
	RFID_MID_GETTAGREPORTPARA = 0x0A,
	RFID_MID_SETEPCBASEPARA = 0x0B,
	RFID_MID_GETEPCBASEPARA = 0x0C,
	RFID_MID_SETINTERVALREADMODE = 0x0D,
	RFID_MID_GETAUTOMODE = 0x0E,
	RFID_MID_READEPC = 0x10,
	RFID_MID_WRITEEPC = 0x11,
	RFID_MID_LOCKEPC = 0x12,
	RFID_MID_DESTORYECP = 0x13,
	RFID_MID_MONZAQT = 0x14,
	RFID_MID_SUPPERRWEPC = 0x1A,
	RFID_MID_READ6B = 0x40,
	RFID_MID_WRITE6B = 0x41,
	RFID_MID_LOCK6B = 0x42,
	RFID_MID_LOCKQUERY6B = 0x43,
	RFID_MID_READGB = 0x50,
	RFID_MID_WRITEGB = 0x51,
	RFID_MID_LOCKGB = 0x52,
	RFID_MID_DESTORYGB = 0x53,
	RFID_MID_STOP = 0xFF,
#endif

#if REGION("RFID配置消息自动上报命令")
	RFID_MID_EPCREPORT = 0x00,
	RFID_MID_EPCOVER = 0x01,
	RFID_MID_CURANT = 0x02,
	RFID_MID_6BREPORT = 0x20,
	RFID_MID_6BOVER = 0x21,
	RFID_MID_GBREPORT = 0x30,
	RFID_MID_GBOVER = 0x31,
#endif
	
}MsgId;

#ifdef __cplusplus
}
#endif

#endif